### ISSUE TITLE
Bug: Excessive memory usage

### ISSUE THREAD

**Issue by naveensingh** [awxkee/jxl-coder-glide#4]
Hello!

This plugin was recently added to Fossify Gallery (https://github.com/FossifyOrg/Gallery/pull/253) but it appears to be cause excessive memory usage (see https://github.com/FossifyOrg/Gallery/issues/301). This affects all users including those without JXL images.

I did a little digging and found that the `JxlCoderStreamDecoder.handles()` method seems to use a lot of memory for the `isJXL()` check. Some more info in the call stack:

<img src="https://github.com/user-attachments/assets/33b63290-b192-49f2-bdd1-db6382a3779e" width=1080 />

Thanks.

**Comment by awxkee** [comment]
Hi!

I took check from official glide avif integration. 
Even the behaviour looked greedy I decided that's ok if they keep it.
Does glide avif have the same behaviour if you have one?

I'll change checking strategy soon.

**Comment by naveensingh** [comment]
> Does glide avif have the same behaviour if you have one?

Nope, it doesn't seem to happen with AVIF. AVIF support was added months ago (https://github.com/FossifyOrg/Gallery/pull/159) and there haven't been any such reports until now. 

> I'll change checking strategy soon.

Thanks!

**Comment by awxkee** [comment]
Try out `2.3.0.1` version. I thinks it should fine

**Comment by naveensingh** [comment]
Thanks for the quick fix! I did some quick testing and it appears to be fixed. I will do some more testing later.

**Comment by naveensingh** [comment]
I did some more tests and yep, it's fixed now. Thanks!
