### ISSUE TITLE
Bug: Can't use recent versions from Jitpack?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [awxkee/jxl-coder-glide#5]
The repository's page says to use:

```
implementation 'com.github.awxkee:jxl-coder-glide:2.1.9' // or any version above picker from release tags
```

But there are newer versions, such as 2.3.0.1:

https://github.com/awxkee/jxl-coder-glide/releases

And it's also on Jitpack:

https://jitpack.io/#awxkee/jxl-coder-glide

Thing is, it says we can't use the recent versions:

![image](https://github.com/user-attachments/assets/eda40600-7519-49f2-ad06-75ccacb73edf)

How come?
How can we use them?

**Comment by awxkee** [comment]
From 2.2.0 only maven central versions are published

**Comment by awxkee** [comment]
You can publish your own fork on jitpack if there is some requirement

**Comment by AndroidDeveloperLB** [comment]
@awxkee But the repository's page says this:

```
    maven { url "https://jitpack.io" }
```

So I use this in the settings.gradle.kts file:

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = URI.create("https://jitpack.io") }
    }
}
```

I did something wrong?

**Comment by awxkee** [comment]
Read title where it is written that it was deprecated

**Comment by AndroidDeveloperLB** [comment]
@awxkee I have it already from other dependencies that do use Jitpack. How can I use the one here properly?
Why is it deprecated? Why can't we use the latest version?

**Comment by awxkee** [comment]
Because it's easier for me to make CI from one place, and do not have to solve multiple build issues on CI and jitpack separately.
Why don't ask to update your dependency then? I moved everything to maven central almost a year ago.

**Comment by AndroidDeveloperLB** [comment]
@awxkee The post is about updating the dependency, as I can't do it.
When I try, the IDE says it can't find them. I already use mavencentral as you can see above.

This is what I tried:

```
    implementation("com.github.awxkee:jxl-coder-glide:2.3.0.1")
```

And this is what I got, so I can't build the project using it:

```
Configuration cache state could not be cached: field `compileTimeDependencies` of task `:app:dataBindingMergeDependencyArtifactsDebug` of type `com.android.build.gradle.internal.tasks.databinding.DataBindingMergeDependencyArtifactsTask`: error writing value of type 'org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection'
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.awxkee:jxl-coder-glide:2.3.0.1.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Ask Gemini
```

**Comment by awxkee** [comment]
I’ve completely lost a track already what are you trying to do.
Did you try maven central?it is definitely have different form _implementation 'io.github.awxkee:jxl-coder-glide:2.3.0.1'_

**Comment by AndroidDeveloperLB** [comment]
@awxkee The issue stayed the same as the title and the first post of this thread: I can't use the latest version of the dependency. Doesn't matter if it's from Jitpack or mavencentral, as I have them both defined already.

It says on the release page of the repository that the latest version is 2.3.0.1, so that's what I tried according to the instructions of the main page of the repository, meaning to replace the numbers accordingly to 2.3.0.1, and the result is a build failure as I wrote here:

https://github.com/awxkee/jxl-coder-glide/issues/5#issuecomment-2551882000

**Comment by awxkee** [comment]
Maven central version published and works.
https://central.sonatype.com/artifact/io.github.awxkee/jxl-coder-glide

You snippet tries to load jitpack version. Note group name is different for maven central and jitpack

**Comment by awxkee** [comment]
> I’ve completely lost a track already what are you trying to do. Did you try maven central?it is definitely have different form _implementation 'io.github.awxkee:jxl-coder-glide:2.3.0.1'_

If this does work that means issue somewhere on your side

**Comment by AndroidDeveloperLB** [comment]
@awxkee Seems odd as the project is quite new. 
Here, created a new project and still got the same issue. Please check it out and tell me what's wrong.
Also attached a video there to show the issue, and you can see that when the dependency isn't there, there is no issue, and when it's there, it fails to build.

[My Application.zip](https://github.com/user-attachments/files/18187723/My.Application.zip)

EDIT: You say I used the wrong dependency? But that's what the repository's main page says...

**Comment by AndroidDeveloperLB** [comment]
So anyway, when using this, it works:

implementation("io.github.awxkee:jxl-coder-glide:2.3.0.1")

Please update the repository's instructions. They are outdated and wrong as we can't use latest version of the dependency this way.

**Comment by awxkee** [comment]
Main page clearly says jitpack is deprecated since 2.2.0 :)

**Comment by AndroidDeveloperLB** [comment]
That's not the part I said that is wrong. That's actually the only part there that is correct...
The part that's wrong is anything related to using the dependency. It should be:

```
implementation("io.github.awxkee:jxl-coder-glide:2.3.0.1")
```

Please fix it.

**Comment by awxkee** [comment]
Do a PR? I still haven’t get what exactly you want from me because this is specified in readme

**Comment by AndroidDeveloperLB** [comment]
As I wrote, the readme is wrong, as it mentions something that can't be used anymore. So the issue isn't completed and should be closed. It says it's deprecated, but doesn't say what to use instead. Reminds me of what Google often does...
:)

As for PR, here:
https://github.com/awxkee/jxl-coder-glide/compare/master...AndroidDeveloperLB:jxl-coder-glide:master?expand=1

I hope you understood what I did there.

**Comment by awxkee** [comment]
Yes, but I don't understand why you look there instead of [here](https://github.com/awxkee/jxl-coder-glide?tab=readme-ov-file#add-repository) ( Add repository section )

**Comment by awxkee** [comment]
<img width="950" alt="Screenshot 2024-12-18 at 19 50 31" src="https://github.com/user-attachments/assets/6b7e2cfb-c0c5-4a73-8114-78146fe55e33" />

What is incorrect here?

**Comment by AndroidDeveloperLB** [comment]
Oh sorry about that. For some reason I focused on the wrong section...
Why put the deprecated part though?

**Comment by AndroidDeveloperLB** [comment]
Also why empty "Disclaimer" ?

**Comment by awxkee** [comment]
For someone who wants to check/test/look at/dig into old versions

**Comment by AndroidDeveloperLB** [comment]
I see. Sorry for all the trouble.
Maybe you should merge them. Can't add the changes from old place to the new one?

**Comment by awxkee** [comment]
> Also why empty "Disclaimer" ?

It’s disclaimer for section JPEGXL below :)

**Comment by AndroidDeveloperLB** [comment]
The disclaimer is to reach the next section?
:)

**Comment by awxkee** [comment]
> The disclaimer is to reach the next section? :)

Yes :)



> I see. Sorry for all the trouble. Maybe you should merge them. Can't add the changes from old place to the new one?

What for actually merge them? It is a lot of routine for doing so, but could be needed just for a few times. 
I'll might drop deprecated section on next update.
However, next update might be delayed by https://github.com/libjxl/libjxl/issues/3887.
Until libjxl issue is resolved there is low value ( if not negative ) to me to put any efforts to this repo.

**Comment by AndroidDeveloperLB** [comment]
I see. I've now tried to compare the new version from mavencentral and the one of Jitpack. seems the new one is more than x2 slower in decoding (2866ms on new compared to 1014ms in the old). Tested on Pixel 6 with Android 15. 

How come?
I was actually hoping to have it faster, as 1 second it quite a lot...

I've tested on this image:

[cow_image_jxl.zip](https://github.com/user-attachments/files/18188290/cow_image_jxl.zip)

Code to test:

```
val startTime = SystemClock.elapsedRealtime()
val maxDisplaySize = Point(1080, 2400) // original code here is getting the screen size
Log.d("AppLog", "maxDisplaySize:$maxDisplaySize ")
Glide.with(activity!!.applicationContext)
        .load(R.raw.cow_image_jxl)
        .override(maxDisplaySize.x, maxDisplaySize.y)
        .diskCacheStrategy(DiskCacheStrategy.NONE)
        .centerCrop()
        .addListener(object : RequestListener<Drawable> {
            override fun onLoadFailed(e: GlideException?, model: Any?, target: Target<Drawable?>, isFirstResource: Boolean): Boolean {
                Log.d("AppLog", "onLoadFailed $e")
                return false
            }

            override fun onResourceReady(resource: Drawable, model: Any, target: Target<Drawable?>?, dataSource: DataSource, isFirstResource: Boolean): Boolean {
                Log.d("AppLog", "onResourceReady image size:${resource.intrinsicWidth}x${resource.intrinsicHeight} time:${SystemClock.elapsedRealtime() - startTime} memory usage:${(resource as BitmapDrawable).bitmap.allocationByteCount}")
                return false
            }

        }).submit()
```

**Comment by awxkee** [comment]
Jxl images is slow. I’ve personally improved significantly decoding on my side in the latest versions, might be there another something in libjxl.
Open another issue for this, I’ll look when I’ll have time.
For the speed, I once said you Avif is better. Do not expect Jxl images to be really fast.

**Comment by AndroidDeveloperLB** [comment]
Wait how do you remember me...
You have a great memory...
Anyway, I wanted to try various images formats as I want both storage saving and decoding speed. 
Maybe I will go back to JPG, as it seems faster than both AVIF and JPEG-XL in this case. There are some services to optimize it a bit in storage space.
Or maybe I will choose my choice per image...

Here, new report:
https://github.com/awxkee/jxl-coder-glide/issues/7

**Comment by awxkee** [comment]
Thanks for another issue I guess :)

AVIF will be fastest overall when properly done on decoding, and fantastically bad on encoding.
JPEG xl bad on both cases, where it is good it is only very high quality.
Here is some https://github.com/awxkee/jpegli-coder jpegli built for android, I can’t say that it is fully featured but it’s definitely works. And you can use standard android decoder.

**Comment by awxkee** [comment]
There is some different modes of encoding, better check some jpegli documentation what does it actually mean if you’re interested

**Comment by AndroidDeveloperLB** [comment]
The image I've provided is of quite a high quality though. 2590x3453.
As for AVIF being fast, I've also compared it to JPEG:
JPEG : took 226 ms. 
AVIF: took 531 ms.

So still JPEG was faster. Maybe it's related to running on Android. Maybe on PC it's different.

It's the same cow image I've provided. This is in gradle:

```
    // https://bumptech.github.io/glide/doc/download-setup.html#kotlin---ksp   https://bumptech.github.io/glide/int/avif.html
    val glideVersion = "4.16.0"
    implementation("com.github.bumptech.glide:glide:${glideVersion}")
    ksp ("com.github.bumptech.glide:ksp:${glideVersion}")
    implementation ("com.github.bumptech.glide:avif-integration:4.16.0")
```

image files:

[images.zip](https://github.com/user-attachments/files/18188747/images.zip)

I don't think I can use "standard android decoder" as you wrote. Android doesn't support JPEG-XL:
https://developer.android.com/media/platform/supported-formats#image-formats
I'm interested in decoding. The encoding is done on my PC or via web browser anyway.

**Comment by awxkee** [comment]
Jpegli encodes standard jpegs. Read some paper from google about that. 
To leverage full advantage of avifs you’ll have to recompile everything yourself with libdav1d and libyuv integrated, default glide implementation is very basic. However, encoding will be still drastically slow it still have no reason put efforts on this.

**Comment by AndroidDeveloperLB** [comment]
I think the comparison I made is wrong, as I've put the JPEG file into drawable-xxhdpi. 
I've now put it in drawable-nodpi, and it took 553 ms. So about the same as AVIF...

Android supported AVIF from some version. Do you think it's faster than Glide? Or maybe Glide uses it already when possible?

**Comment by awxkee** [comment]
I don't for sure how it is done in glide, I looked once only at their plugin. Perhaps if you're not adding the plugin and your device is capable to handle AVIF's it should handle them.

**Comment by AndroidDeveloperLB** [comment]
I tried to use BitmapFactory on the AVIF file and see what happens, but then I got NPE on the bitmap as it failed to decode it (And I have Android 15...) . Weird:

```
thread {
    val inputStream = resources.openRawResource(R.raw.cow_image)
    inputStream.use {
        val bitmap = BitmapFactory.decodeStream(inputStream)
        Log.d("AppLog", "onResourceReady image size:${bitmap.width}x${bitmap.height} time:${SystemClock.elapsedRealtime() - startTime} memory usage:${bitmap.allocationByteCount}")
    }
}.start()
```

**Comment by AndroidDeveloperLB** [comment]
Trying what you said, to remove the AVIF dependency of Glide, it also failed to decode it.

**Comment by AndroidDeveloperLB** [comment]
About the encoder, here's a better website, I think:
https://www.jpegliconverter.com/

**Comment by awxkee** [comment]
Mine encoder is for in-app if need it
